### ISSUE TITLE
Failed to announce resource pack, resourcePackInfo is null

### ISSUE THREAD

**Issue by erxson** [apyrr/spigot-chatemotes#2]
Console log:
```
[11:20:30 INFO]: ericsson_ issued server command: /emote refresh
[11:20:30 INFO]: [ChatEmotes] Loaded 4 emotes from LocalEmoteProvider:
[11:20:30 INFO]: [ChatEmotes] OMEGALUL, EZ, KEKW, Sadge
[11:20:30 WARN]: [ChatEmotes] Failed to announce resource pack, resourcePackInfo is null
```
Config:
```
strict-emote-names: false

use-emotes-in:
  chat: true
  signs: true
  books: true
  anvils: true
  player-names: false

page-size: 14

emote-provider:
  use: local
  local:
    pack:
      prompt: Chat emotes!
      height: 10
      ascent: 8
    http:
      hostname-override: *serverip*
      port: 25618
```

Help me, please

**Comment by apyrr** [comment]
Hey! I've added some logging which will help you understand why resource pack is failing to announce.
But it looks like your resource pack server port (25618 in your case) is closed for incoming connections.
You should also move `hostname-override` property to `emote-provider.local` block ([example here](https://github.com/apyrr/spigot-chatemotes/blob/430102e45e866b0516c4e3a465de82874abe4501/src/main/resources/config.yml#L28)).

**Comment by erxson** [comment]
Та я тупо захостил уже апи
